---
latitude: 40.75664
longitude: -73.9843
map_zoom: 12
name: AKA Times Square
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 123 West 44th Street
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10036'
_hotel_id: AKA252
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
